USE DB01;
CREATE TABLE CUSTOMERS03 (CUSTOMER_ID INT PRIMARY KEY,
						  CUSTOMER_NAME VARCHAR(100) NOT NULL,
                          CITY          VARCHAR(50)  NOT NULL,
                          REGISTRATION_DATE DATE     NOT NULL);
 INSERT INTO CUSTOMERS03 VALUES 
 ( 1,'ARUN','KOCHI','2024-01-10'),
 (2,'MEERE','KOCHI','2024-02-15'),
 (3,'RAHUL','TRIVANDRUM','2024-03-20'),
 (4,'ANJALI','CALICUT','2024-04-12'),
 (5,'NEHA','KOCHI','2024-05-18'),
 (6,'AKASH','TRIVANDRUM','2024-06-22'),
 (7,'RIYA','CALICUT','2024-07-01'),
 (8,'VIVEK','KOCHI','2024-08-10');
 SELECT*FROM CUSTOMERS03;
 CREATE TABLE RESTAURANTS (RESTAURANT_ID INT primary KEY,
						  RESTAURANT_NAME VARCHAR(100) NOT NULL,
                          CITY            VARCHAR(50)  NOT NULL,
                          RATING          DECIMAL (2,1) CHECK (RATING<=5));
INSERT INTO restaurants VALUES 
(101 ,'Spice Hub' ,'Kochi',4.5),
(102, 'pizza town','kochi',4.2),
(103, 'burger point','trivandrum',4.0),
(104, 'curry house','calicut',4.8),
(105,'food court','kochi',3.9);
select*from restaurants;
create table delivery_agent(agent_id int primary key,
							agent_name varchar(100) not null,
                            joining_date  date not null);
insert into delivery_agent values
(201,'ajay','2023-01-10'),
(202,'manu','2023-05-14'),
(203,'suresh','2024-02-11'),
(204,'deepak','2024-06-18');
select*from delivery_agent;
DROP TABLE orders01;
create table orders01 (order_id int primary key,
							customer_id int ,
                            restaurant_id int,
                            agent_id int ,
                            FOREIGN KEY (customer_id) REFERENCES customers03(customer_id),
                            FOREIGN KEY (restaurant_id) REFERENCES restaurants(restaurant_id),
                            foreign key(agent_id) references delivery_agent(agent_id),
                            order_amount decimal(10,2) not null,
                            order_timestamp timestamp not null,
                            delivery_timestamp timestamp not null);
INSERT INTO ORDERS01 VALUES
(1001, 1, 101, 201, 550, '2025-01-05 10:30:00', '2025-01-05 11:00:00'),
(1002, 2, 102, 202, 350, '2025-01-05 12:00:00', '2025-01-05 12:35:00'),
(1003, 3, 103, 203, 700, '2025-01-06 13:15:00', '2025-01-06 14:00:00'),
(1004, 1, 101, 201, 450, '2025-01-06 18:20:00', '2025-01-06 18:55:00'),
(1005, 4, 104, 204, 900, '2025-01-07 19:10:00', '2025-01-07 19:50:00'),
(1006, 5, 105, 202, 300, '2025-01-08 20:00:00', '2025-01-08 20:40:00'),
(1007, 6, 103, 203, 650, '2025-01-09 14:00:00', '2025-01-09 14:45:00'),
(1008, 7, 104, 204, 800, '2025-01-10 21:00:00', '2025-01-10 21:35:00'),
(1009, 8, 102, 201, 420, '2025-01-11 17:00:00', '2025-01-11 17:28:00'),
(1010, 1, 101, 202, 600, '2025-01-12 13:00:00', '2025-01-12 13:38:00');
select*from orders01;
-- 1 ,Show all customers and the orders they have placed
SELECT c.customer_id,
       c.customer_name
	FROM customers03 c
JOIN orders01 o
ON c.customer_id = o.customer_id;
-- 2, Show customers who have never placed an order.
select c.customer_id,c.customer_name,o.order_id
from customers03 c left join orders01 o
on c.CUSTOMER_ID = o.customer_id
where o.order_id is null;
-- 3, Show all restaurants and their corresponding orders
select r.restaurant_id,r.restaurant_name,o.order_id
from restaurants r  join orders01 o
on r.restaurant_id = o.restaurant_id;
-- 4, Find the total revenue generated by each restaurant
select r.restaurant_id,r.restaurant_name,
sum(o.order_amount) as total_order_amount
from  restaurants r join orders01 o
on r.RESTAURANT_ID = o.restaurant_id
group by r.RESTAURANT_ID,r.RESTAURANT_NAME
order by total_order_amount desc;
-- 5, Find the customer who spent the highest amount overall.
SELECT c.customer_id,
       c.customer_name,O.ORDER_ID,
       SUM(o .ORDER_amount) AS total_spent
FROM customers03 c
JOIN orders01 o 
ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name,O.ORDER_ID
HAVING SUM(o .ORDER_amount) = (
    SELECT MAX(total_spent)
    FROM (
        SELECT customer_id, SUM(O.ORDER_amount) AS total_spent
        FROM orders01
        GROUP BY customer_id
    ) AS subquery
);
DESCRIBE orders01;
-- 6, Find customers whose total spending is greater than the average customer spending.
select c.customer_id,
       c.customer_name,
       sum(o.order_amount) as total_spend
       from customers03 c
       join orders01 o
       on c.customer_id=o.customer_id
       group by c.customer_id,c.customer_name
       having sum(o.order_amount) > (
       select avg(total_spent)
       from (
       select customer_id,sum(order_amount) as total_spent
       from orders01
       group by customer_id
       ) as subquery);
-- 7, Find restaurants earning more revenue than the average restaurant revenue
select r.restaurant_id,restaurant_name,
       sum(o.order_amount) as total_revenue
       from  restaurants r join orders01 o
	   on r.restaurant_id = o.restaurant_id
       group by r.restaurant_id,r.restaurant_name
       having sum(o.order_amount) > (
       select avg(total_rev)
       from (
       select restaurant_id, sum(order_amount) as total_rev
       from orders01
       group by restaurant_id
       ) as subquery
       ) 
       order by total_revenue desc;
-- 8,    Find delivery agents who completed more deliveries than the average number of  deliveries  
select d.agent_name,
count(o.order_id) as total_deliveries
from orders01 o join delivery_agent d
on d.agent_id = o.agent_id
group by d.agent_name
having count(o.order_id) > (
select avg(agent_deliveries)
from (
SELECT COUNT(order_id) AS agent_deliveries
        FROM orders01
        GROUP BY agent_id
    ) AS sub
);
-- 9, Find the restaurant that generated the highest revenue.
select r.restaurant_id,r.restaurant_name,
sum(o.order_amount) as hieghest_revenue
from orders01 o join restaurants r
on o.restaurant_id = r.restaurant_id
group by r.restaurant_id,restaurant_name
order by hieghest_revenue desc
limit 1;
 -- 10  Find the city generating the highest order revenue.
 select c.city,
 sum(o.order_amount) as total_revenue
 from orders01 o join customers03 c
 on c.customer_id= o.customer_id
 group by c.city
 order by total_revenue desc
 limit 1;
-- 11  Display monthly revenue generated by the business.

SELECT YEAR(order_timestamp) AS year,
       MONTH(order_timestamp) AS month,
       SUM(order_amount) AS monthly_revenue
FROM orders01
GROUP BY YEAR(order_timestamp), MONTH(order_timestamp)
ORDER BY YEAR(order_timestamp), MONTH(order_timestamp);
SELECT DATE_FORMAT(order_timestamp, '%b-%y') AS month,
       SUM(order_amount) AS monthly_revenue
FROM orders01
GROUP BY DATE_FORMAT(order_timestamp, '%b-%y')
ORDER BY MIN(order_timestamp);

-- Q12, Display daily order counts.
select date(order_timestamp) as order_date,
       count(*) as daily_order_count
       from orders01
       group by date(order_timestamp)
       order by order_date;
 
--  q13,Display yearly revenue trends
select year(order_timestamp) as order_year,
           sum(order_timestamp) as total_revenue
           from orders01
           group by year(order_timestamp)
           order by total_revenue;

-- q 14,Identify the busiest ordering day.
select date(order_timestamp) as order_day,
count(*) as order_count
from orders01
group by date(order_timestamp)
order by order_count desc
limit 1;
-- q15,Identify the busiest ordering hour.
select hour(order_timestamp) order_hour,
count(*) as order_count
from orders01
group by hour(order_timestamp)
order by order_count desc
limit 1;
-- q16,Calculate delivery duration for every order.
select order_id, timestampdiff(minute,order_timestamp,delivery_timestamp) as delivery_duration
from orders01;
-- q17, Find the average delivery time for each delivery agent.
select d.agent_name,avg(timestampdiff(minute,o.order_timestamp,o.delivery_timestamp)) as avg_delivery_time_minute
from orders01 o
join delivery_agent d
on d.agent_id = o.agent_id
group by d.agent_name
order by avg_delivery_time_minute;
-- q18,Identify the fastest delivery agent.	
	select d.agent_name,avg(timestampdiff(minute,o.order_timestamp,o.delivery_timestamp)) as avg_delivery_time_minute
from orders01 o
join delivery_agent d
on d.agent_id = o.agent_id
group by d.agent_name
order by avg_delivery_time_minute asc
limit 1;
-- q19,Identify the slowest delivery agent.	
select d.agent_name,avg(timestampdiff(minute,o.order_timestamp,o.delivery_timestamp)) as avg_delivery_time_minute
from orders01 o
join delivery_agent d
on d.agent_id = o.agent_id
group by d.agent_name
order by avg_delivery_time_minute desc
limit 1;
-- q20,Rank restaurants based on total revenue.
select r.restaurant_name,
                  sum(o.order_amount) as total_revenue,
                  RANK() OVER (ORDER BY SUM(o.order_amount) DESC) AS revenue_rank
FROM restaurants r
JOIN orders01 o ON r.restaurant_id = o.restaurant_id
GROUP BY r.restaurant_name;
-- Q21,  Rank customers based on total spending.
SELECT c.customer_name,c.customer_id,
       SUM(o.order_amount) AS spending_amount,
       RANK() OVER (ORDER BY SUM(o.order_amount) DESC) AS spending_rank
FROM customers03 c
JOIN orders01 o
ON c.customer_id = o.customer_id
GROUP BY c.customer_name,c.customer_id;
-- q,22  Assign sequence numbers to orders placed by each customer.
select c.customer_name,c.customer_id,o.order_timestamp,
row_number()over(partition by c.customer_id order by o.order_timestamp desc) as order_sequence
from orders01 o
join customers03 c
on c.customer_id = o.customer_id;
-- q23, Show each customer's current order amount along with their previous order amount.
select c.customer_name,o.order_id,o.order_amount,
lag(o.order_amount)over(partition by c.customer_id) as previous_order_amount
from orders01 o
join customers03 c
on c.customer_id = o.customer_id;
-- q24 Show each customer's current order amount along with their next order amount.
select o.order_id,o.order_amount,
lead(o.order_amount)over(partition by c.customer_id) as next_order_amount
from orders01 o
join customers03 c
on c.customer_id = c.customer_id;
-- q25, Calculate cumulative revenue generated over time.
select order_id,order_amount,
sum(order_amount)
over(order by order_id ) as cumulative_revenue
from orders01;
-- q26, Calculate moving average revenue over the last three orders.
select order_id,order_amount,
avg(order_amount)
over(order by order_id rows 2 preceding) as moving_average_revenue
from orders01;
-- q27, Find the top 3 restaurants by revenue.
select r.restaurant_name,
sum(o.order_amount) as total_revenue
from orders01 o
join restaurants r
on r.restaurant_id = o.restaurant_id
group by r.restaurant_name
order by sum(o.order_amount) desc
limit 3;
 -- q28,Find the top 5 customers by spending
 select c.customer_name,
 sum(o.order_amount) as spending_amount
 from orders01 o
 join customers03 c
 on c.customer_id = o.customer_id
 group by c.customer_name
 order by sum(o.order_amount) desc
 limit 5;
 -- q29,Identify customers who placed more than one order.
 select c.customer_name,
 count(o.order_id) as order_count
 from orders01 o
 join customers03 c
 on c.customer_id = o.customer_id
 group by c.customer_name
 having count(o.order_id)>1;
 -- q30,Identify restaurants receiving more than five orders.
 select restaurant_name,
 count(o.order_id) as order_count
 from orders01 o
 join restaurants r
 on r.restaurant_id =o.restaurant_id
 group by r.restaurant_name
 having count(o.order_id)>5;
-- q31, Find newly registered customers during the last six months
SELECT customer_name
FROM customers03
WHERE registration_date between '2024-03-01' AND '2024-08-31';
-- Q32,Find delivery agents who joined this year.
select agent_name
from delivery_agent
where year(joining_date) = 2025;
-- q33, Find orders placed during weekends.
select order_id
from orders01
 where weekday(order_timestamp) in (5,6);
  -- q34,Find orders placed during weekdays.
 select order_id
 from orders01
 where weekday(order_timestamp) in (0,6);
-- q35,Find orders delivered within 30 minutes.
select order_id
from orders01
where timestampdiff(minute , order_timestamp,delivery_timestamp)<=30;
-- q36,Find orders taking more than 45 minutes for delivery.
select order_id
from orders01
where timestampdiff(minute,order_timestamp,delivery_timestamp) >=45;
-- q37,Display cities where customers are present.
select distinct city
from customers03;
-- q38,Display cities where restaurants are present.
select distinct city
from restaurants;
-- q39,Display all cities involved in the business ecosystem.
select distinct c.city
from customers03 c 
 join restaurants r 
on r.city= c.city;
-- q40,Display cities having both customers and restaurants.
select distinct c.city
from customers03 c 
 join restaurants r 
on r.city= c.city;
-- q41, Display cities having customers but no restaurants.
select distinct c.city
from customers03 c
left join restaurants r 
on c.city = r.city
where r . city is null;
-- q42, Display cities having restaurants  but no customers.
select distinct r.city
from restaurants r 
right join customers03 c 
on c.city = r.city
where c.city is null;
-- q43, Find the percentage contribution of each restaurant to total company revenue.

SELECT 
    r.restaurant_name,
    SUM(o.order_amount) AS total_revenue,
    (SUM(o.order_amount) * 100.0 / 
        (SELECT SUM(order_amount) FROM orders01)) AS percentage_contribution
FROM restaurants r
JOIN orders01 o 
    ON r.restaurant_id = o.restaurant_id
GROUP BY r.restaurant_name
order by percentage_contribution desc;
-- q44, Find each restaurant's revenue difference from the highest earning restaurant.

SELECT 
    r.restaurant_name,
    SUM(o.order_amount) AS total_revenue,
    (MAX(SUM(o.order_amount)) OVER() - SUM(o.order_amount)) AS revenue_difference
FROM restaurants r
JOIN orders01 o 
    ON r.restaurant_id = o.restaurant_id
GROUP BY r.restaurant_name
ORDER BY revenue_difference asc;
-- q45,Find the first order placed by every customer.
SELECT 
    MONTH(o.order_timestamp) AS order_month,
    SUM(o.order_amount) AS total_revenue,
    (SUM(o.order_amount) - 
     LAG(SUM(o.order_amount)) OVER (ORDER BY MONTH(o.order_timestamp))) AS difference_vs_previous
FROM orders01 o
GROUP BY MONTH(o.order_timestamp)
ORDER BY order_month;
-- q46, Find the first order placed by every customer.
select c.customer_name,o.order_id,
min(o.order_timestamp) as first_order_timestamp
from orders01 o 
join customers03 c 
on o.order_id= o.order_id
group by c.customer_name,o.order_id
order by first_order_timestamp asc;
-- q47,Find the latest order placed by every customer.
select c.customer_name,o.order_id,
min(o.order_timestamp) as first_order_timestamp
from orders01 o 
join customers03 c 
on o.order_id= o.order_id
group by c.customer_name,o.order_id
order by first_order_timestamp desc;
-- q48, Find restaurants whose revenue is consistently above average.
SELECT r.restaurant_id,
       r.restaurant_name,
       AVG(o.order_amount) AS avg_restaurant_revenue
FROM restaurants r
JOIN orders01 o 
  ON r.restaurant_id = o.restaurant_id
GROUP BY r.restaurant_id, r.restaurant_name
HAVING MIN(o.order_amount) > (
    SELECT AVG(order_amount) 
    FROM orders01
);
 -- q49, Find customers whose spending increased compared to their previous order.
SELECT customer_id,
       customer_name,
       order_id,
       order_timestamp,
       order_amount,
       previous_order_amount
FROM (
    SELECT 
        c.customer_id,
        c.customer_name,
        o.order_id,
        o.order_timestamp,
        o.order_amount,
        LAG(o.order_amount) OVER(
            PARTITION BY c.customer_id 
            ORDER BY o.order_timestamp
        ) AS previous_order_amount
    FROM customers c
    JOIN orders01 o 
      ON c.customer_id = o.customer_id
) t
WHERE t.previous_order_amount IS NOT NULL
  AND t.order_amount > t.previous_order_amount;

 -- q50,Prepare a management dashboard query showing:
-- Total Customers: 
-- Total Restaurants:
-- Total Delivery Agents:
-- Total Orders:
-- total revenue
-- AveRAGE order value   
with dashboard as (
select count(distinct c.customer_id) as total_customer,
	   count(distinct r. restaurant_id) as total_restaurant,
       count(distinct d. agent_id) as total_delivery_agent,
       sum(order_amount) as total_revenue,
       avg(order_amount) as avg_revenue
       from orders01 o 
       join customers03 c 
       on o.customer_id = c.customer_id
       join restaurants r 
       on r.restaurant_id = o.restaurant_id
       join delivery_agent d 
       on o.agent_id = d.agent_id 
       )
       select*from dashboard;